config/routes.rb
Rails.application.routes.draw do
	root 'products#index'
	resources :products
	resources :users, only: [:new, :create]
	resources :sessions, only: [:new, :create, :destroy]
	resources :products do
		 resources :reviews, only: [:show, :create, :destroy]
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end

	has_many :reviews
	has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates :comment, presence: true
	# validate :blank_review
	#
	# def blank_review
	# 	if comment.blank?
	# 		errors.add[:comment, "You cannot submit a blank review!"]
	# 	end
	# end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, through: :reviews
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	 def ensure_logged_in
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_session_path
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	 def index
		@products = if params[:search]
			Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
		else
			Product.all
		end
	end

 respond_to do |format|
		format.html
		format.js
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end

	def edit
		@product = Product.find(params[:id])
	end

	def create
		@product = Product.find(params[:id])

		if @product.save
			redirect_to products_url
		else
			render :new
		end
	end

	def update
		@product = Product.find(params[:id])

		if @product.update_attributes(product_params)
			redirect_to product_path(@product)
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end

	def show
		@product = Product.find(params[:id])
		if current_user
		@review = @product.reviews.build
		end
	end

	private
	def product_params
		params.require(:product).permit(:name, :description, :price_in_cents)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :ensure_logged_in, only: [:create, :destroy]
	before_action :load_product

	def show
		@review = Review.find(params[:id])
	end

	def create
		@review = @product.reviews.build(review_params)
		@review.user = current_user

		if @review.save
			respond_to do |format|
			if @review.save
				format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
				format.js {} # This will look for app/views/reviews/create.js.erb
			else
				format.html { render 'products/show', alert: 'There was an error.'  }
				format.js {} # This will look for app/views/reviews/create.js.erb
			end
			end
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
	end

	private
	def review_params
		params.require(:review).permit(:comment, :product_id)
	end

	def load_product
		@product = Product.find(params[:product_id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		# empty because we're not instantiating a user object here
	end

	def create
			user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to products_url, notice: "Logged in!"
		else
			flash.now[:alert] = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to products_url, notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to products_url, notice: "Signed Up!"
		else
			render "new"
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>
 <body>

		<%= link_to "Home", root_path %>

		<% if flash[:notice] %>
			<p id="notice"><%= flash[:notice] %></p>
		<% end %>
		<% if flash[:alert] %>
			<p id="alert"><%= flash[:alert] %></p>
		<% end %>

		<%= yield %>
	<p class="userinfo">
			<% if current_user %>
				Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end %>
		</p>
	</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :price_in_cents %><br />
		<%= f.number_field :price_in_cents %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/products/_product.html.erb
<ul>
	<li><%= link_to product.name, product_path(product) %></li>
	<li><%= product.description %></li>
	<li><%= product.formatted_price %></li>
	<%= link_to "Edit Product", edit_product_path(product) %>
</ul>

app/views/products/_review_form_errors.html.erb
 <% if @review.errors.present? %>
		<% @review.errors.full_messages.each do |error| %>
			<div class="alert">
				<%= error %>
			</div>
		<% end %>
	<% end %>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
	<div class='review'>
			<p class='comment'>
					 <%= review.comment %>
							<br>
								 <% if review.user != nil %>
										<em> Posted by: <%= review.user.email %></em>
										 Added on: <%= review.created_at %>
					<% end %>
			</p>
	</div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "Add New Product", product_path(:new) %>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search" %>
<% end %>

<div id="products">
	<%= render @products %>
</div>

app/views/products/index.js.erb
$('#products').html("<%=j (render @products) %>");

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Return to Products Page', products_path %>

app/views/products/show.html.erb
<div>
	<%= render @product %>
</div>

 <h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p>


<div id='review-list'>
		<%= render :partial => 'reviews' %>
</div>

<div id='test-form'>
	<% if current_user %>
	<h4>New Review</h4>
	<%= form_for([@product, @review], :remote => true) do |f| %>
		<div id="review-form-errors">
				<%= render :partial => "/products/review_form_errors" %>
		</div>


		<div class="field">
			<%= f.label :comment %><br />
			<%= f.text_area :comment %>
		</div>

		<div class="actions">
			<%= f.submit "Create Review", id: 'review-submit'%>
		</div>
		<% end %>
</div>

<% else %>
	<p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<%= link_to 'Home', products_path %>


<script type="text/javascript">
// 	$(function() {
// 		 $("#review-submit").click(function(){
// 			 $.ajax({
// 				 beforeSend: function() { // set this code to happen just before the ajax request is made
// 					 $("input[type='submit']").val('Saving...');
// 					 $('input:submit').addClass('loading');
// 				 },
// 				 complete: function(){
// 					 $("input[type='submit']").val('Create Review');
// 						$('input:submit').removeClass('loading');
// 				 }
// 			 })
// 		 })
// });

	$(document).ready(function() {
		 $("#new_review")
				.on('ajax:beforeSend', function() {// set this code to happen just before the ajax request is made
					$("input[type='submit']") // make changes to the submit button
						.val('Saving...') // change the text on the button
						.attr('disabled', 'disabled'); // disable the button
				})
				.on('ajax:complete', function() {// set this code to happen just before the ajax request is made
					$("input[type='submit']")
						.val('Create Review')
						.removeAttr('disabled');
				});
	});
</script>

app/views/products/show.js.erb
$('body').append("<%=j(render @product) %>");

app/views/reviews/_form.html.erb
<%= form_for(@product) do |f| %>

	<div class="field">
		<%= f.text :comment %><br />
		<%= f.text_field :comment %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/reviews/create.html.erb
<h1>Add a New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
	$("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
	$("#review-form-errors").html("");
	$("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");
	$("#new_review")[0].reset();
<% end %>

app/views/reviews/show.html.erb
 <h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p>

	<% @product.reviews.each do |review| %>
		<p>
			<%= review.comment %>
			<br>
			<% if review.user != nil %>
				<em> by <%= review.user.email %></em>
				Added on: <%= review.created_at %>
			<% end %>
		</p>
	<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	 <div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions"><%= f.submit %></div>
<% end %>